# Generated by Django 4.2.7 on 2024-01-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
